// Generate shell helpers in the workdir so the agent can pipe code into a REPL
// instead of quoting it inside curl. They live in .workspace/, which is added to
// the repo's local excludes — the project's own .gitignore is left alone.
import { chmod, mkdir, appendFile, readFile } from "node:fs/promises";

export default async function (ctx: Context, _session: Session | null, _opts?: {}): Promise<string[]> {
    const workdir = ctx.fns.project.workdir({});
    const dir = `${workdir}/.workspace`;
    const port = ctx.fns.config.resolve({ module: "http" }).port;
    const app = ctx.fns.services.status({}).find((s: any) => s.name === "app");
    // The run's secret travels in the helper rather than being looked up: the
    // helper IS the credential, which is why it is regenerated on every start
    // and excluded from the project's git.
    const secret = await ctx.fns.repl.secret({});

    await mkdir(dir, { recursive: true });
    const written = [`${dir}/repl`];
    await Bun.write(`${dir}/repl`, script(port, "the workspace", secret));
    await chmod(`${dir}/repl`, 0o755);

    // An in-process app has no port and no second REPL — the workspace's own is
    // where its functions live.
    if (app?.port && app?.runtime !== "in-process") {
        // The app is its own process with its own secret, next to its own port.
        await Bun.write(`${dir}/app-repl`, script(app.port, "the app", `$(cat "${workdir}/.runtime/repl-secret" 2>/dev/null)`));
        await chmod(`${dir}/app-repl`, 0o755);
        written.push(`${dir}/app-repl`);
    }

    await exclude(workdir);
    return written;
}

// Reads code from arguments or stdin, so both forms work:
//   .workspace/repl 'ctx.fns.services.status({})'
//   .workspace/repl <<'EOF' … EOF
function script(port: number, what: string, secret: string): string {
    return `#!/bin/sh
# Evaluate code inside ${what} (generated by the workspace — do not commit).
# It carries this run's REPL secret: the endpoint refuses anything else, so this
# file is the way in. It is rewritten on every start, when the secret changes.
SECRET="${secret}"
if [ $# -gt 0 ]; then
  printf '%s' "$*" | curl -sS -H "x-repl-secret: $SECRET" "localhost:${port}/repl" --data-binary @-
else
  curl -sS -H "x-repl-secret: $SECRET" "localhost:${port}/repl" --data-binary @-
fi
echo
`;
}

async function exclude(workdir: string): Promise<void> {
    const file = `${workdir}/.git/info/exclude`;
    const existing = await readFile(file, "utf8").catch(() => null);
    if (existing === null || existing.includes(".workspace/")) return;
    await appendFile(file, "\n# workspace-generated helpers\n.workspace/\n");
}
