// Generate shell helpers in the workdir so the agent can pipe code into a REPL
// instead of quoting it inside curl. They live in .workspace/, which is added to
// the repo's local excludes — the project's own .gitignore is left alone.
import { chmod, mkdir, appendFile, readFile } from "node:fs/promises";

export default async function (ctx: Context, _session: Session | null, _opts?: {}): Promise<string[]> {
    const workdir = ctx.fns.project.workdir({});
    const dir = `${workdir}/.workspace`;
    const port = ctx.fns.config.resolve({ module: "http" }).port;
    const app = ctx.fns.services.status({}).find((s: any) => s.name === "app");

    await mkdir(dir, { recursive: true });
    const written = [`${dir}/repl`];
    await Bun.write(`${dir}/repl`, script(port, "the workspace"));
    await chmod(`${dir}/repl`, 0o755);

    if (app?.port) {
        await Bun.write(`${dir}/app-repl`, script(app.port, "the app"));
        await chmod(`${dir}/app-repl`, 0o755);
        written.push(`${dir}/app-repl`);
    }

    await exclude(workdir);
    return written;
}

// Reads code from arguments or stdin, so both forms work:
//   .workspace/repl 'ctx.fns.services.status({})'
//   .workspace/repl <<'EOF' … EOF
function script(port: number, what: string): string {
    return `#!/bin/sh
# Evaluate code inside ${what} (generated by the workspace — do not commit).
if [ $# -gt 0 ]; then
  printf '%s' "$*" | curl -sS "localhost:${port}/repl" --data-binary @-
else
  curl -sS "localhost:${port}/repl" --data-binary @-
fi
echo
`;
}

async function exclude(workdir: string): Promise<void> {
    const file = `${workdir}/.git/info/exclude`;
    const existing = await readFile(file, "utf8").catch(() => null);
    if (existing === null || existing.includes(".workspace/")) return;
    await appendFile(file, "\n# workspace-generated helpers\n.workspace/\n");
}
