// The compose file for one workspace's Aidbox, written by us rather than found
// in the project. A project that only *asks* for Aidbox should not have to carry
// a compose file, a .env and a set of port numbers to get one — and two
// workspaces asking at once must not collide, which is why the volume is named
// after the project and every port comes from the environment the workspace
// assigned.
export default function (_ctx: Context, _session: Session | null, opts: { project: string }): string {
    return `# Generated by the workspace — edits here are lost on the next start.
name: ${opts.project}

services:
  aidbox-db:
    image: postgres:18
    ports: ["\${AIDBOX_DB_PORT}:5432"]
    volumes: ["data:/var/lib/postgresql/18/docker:delegated"]
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: aidbox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidbox"]
      interval: 5s
      timeout: 5s
      retries: 20

  aidbox:
    image: healthsamurai/aidboxone:\${AIDBOX_IMAGE_TAG}
    depends_on:
      aidbox-db: { condition: service_healthy }
    ports: ["\${AIDBOX_PORT}:8080"]
    environment:
      AIDBOX_LICENSE: \${AIDBOX_LICENSE}
      BOX_DB_HOST: aidbox-db
      BOX_DB_PORT: "5432"
      BOX_DB_USER: aidbox
      BOX_DB_PASSWORD: \${POSTGRES_PASSWORD}
      BOX_DB_DATABASE: aidbox
      BOX_WEB_PORT: 8080
      BOX_WEB_BASE_URL: \${AIDBOX_BASE_URL}
      BOX_ADMIN_PASSWORD: \${AIDBOX_ADMIN_PASSWORD}
      BOX_ROOT_CLIENT_SECRET: \${AIDBOX_CLIENT_SECRET}
      BOX_SECURITY_DEV_MODE: "true"
      BOX_BOOTSTRAP_FHIR_PACKAGES: \${AIDBOX_FHIR_PACKAGES}
      BOX_FHIR_COMPLIANT_MODE: "true"
      BOX_FHIR_SCHEMA_VALIDATION: "true"

volumes:
  data:
`;
}
