// Put a chosen Questionnaire into the project: the definition as
// `$qr_<slug>.json`, and the GET/POST pair that renders it and stores what the
// user answers. Ported from the old template's plop generator, minus the parts
// that belonged to that template (seeds, grids, extraction, CDP) — those are
// judgement calls, not scaffolding.
//
// The definition is written first and the routes only point at it, so editing
// the form afterwards is editing one JSON file.
import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export default async function (ctx: Context, _session: Session | null, opts: { slug: string; id?: string; url?: string; file?: string; module?: string }) {
    const slug = kebab(opts.slug ?? "");
    if (!slug) throw new Error("slug is required — it names the file and the route");
    const module = opts.module ?? "patients";

    const questionnaire = await ctx.fns.questionnaire.load({ id: opts.id, url: opts.url, file: opts.file });
    const workdir = ctx.fns.project.workdir({});
    const namespace = Object.keys(ctx.state.appRoots ?? {})[0];
    if (!namespace) throw new Error("no in-process app in workspace.json — nowhere to put the form");

    const definition = `src/${module}/$qr_${slug}.json`;
    const page = `src/${module}/$route_$id_${slug}_GET.ts`;
    const submit = `src/${module}/$route_$id_${slug}_POST.ts`;
    for (const file of [definition, page, submit]) {
        if (await Bun.file(`${workdir}/${file}`).exists()) throw new Error(`${file} already exists — pick another slug`);
    }

    await mkdir(dirname(`${workdir}/${definition}`), { recursive: true });
    await Bun.write(`${workdir}/${definition}`, JSON.stringify({ ...questionnaire, resourceType: "Questionnaire", id: slug }, null, 2) + "\n");
    await Bun.write(`${workdir}/${page}`, pageRoute({ slug, module, namespace, definition, title: questionnaire.title ?? slug }));
    await Bun.write(`${workdir}/${submit}`, submitRoute({ slug, module, namespace, definition }));

    // The app is mounted in this process, so the new routes are live the moment
    // the registry is rebuilt — no restart, no rebuild.
    await ctx.fns.plugins.reload({});
    return { slug, files: [definition, page, submit], route: `/${namespace}/${module}/:id/${slug}` };
}

function pageRoute(o: { slug: string; module: string; namespace: string; definition: string; title: string }): string {
    return `// GET /${o.namespace}/${o.module}/:id/${o.slug} — generated by ctx.fns.questionnaire.generate.
// The form itself is ${o.definition}; edit that file and reload, the route stays.
const FORM = "${o.slug}";
const DEFINITION = "${o.definition}";

export default async function (ctx: Context, _session: Session, opts: { req: Request; params: { id: string } }) {
    const questionnaire = await ctx.fns.questionnaire.load({ file: DEFINITION });
    const rendered = await ctx.fns.questionnaire.render({
        questionnaire,
        submitUrl: \`/${o.namespace}/${o.module}/\${encodeURIComponent(opts.params.id)}/${o.slug}\`,
        formName: FORM,
    });
    return { title: ${JSON.stringify(o.title)}, main: rendered.main };
}
`;
}

function submitRoute(o: { slug: string; module: string; namespace: string; definition: string }): string {
    return `// POST /${o.namespace}/${o.module}/:id/${o.slug} — the form posts to its own url.
// Invalid answers come back as the same form with the errors attached; a valid
// one is stored as a QuestionnaireResponse against the patient.
const FORM = "${o.slug}";
const DEFINITION = "${o.definition}";

export default async function (ctx: Context, _session: Session, opts: { req: Request; params: { id: string } }) {
    const path = \`/${o.namespace}/${o.module}/\${encodeURIComponent(opts.params.id)}/${o.slug}\`;
    const questionnaire = await ctx.fns.questionnaire.load({ file: DEFINITION });
    const rendered = await ctx.fns.questionnaire.render({
        questionnaire,
        submitUrl: path,
        formName: FORM,
        formData: await opts.req.formData(),
    });
    if (!rendered.processResult.submitted || !rendered.processResult.valid) {
        return new Response(rendered.main, { headers: { "content-type": "text/html; charset=utf-8" } });
    }

    const response: any = rendered.response;
    response.resourceType ??= "QuestionnaireResponse";
    response.id ??= \`qr-\${Bun.randomUUIDv7().slice(0, 12)}\`;
    response.subject ??= { reference: \`Patient/\${opts.params.id}\` };
    response.questionnaire ??= questionnaire.url ?? \`Questionnaire/\${FORM}\`;
    response.authored ??= new Date().toISOString();
    response.status = "completed";
    await ctx.fns.${o.namespace}.${o.module}.fhir({ path: \`/fhir/QuestionnaireResponse/\${response.id}\`, method: "PUT", body: response });

    return new Response(null, { status: 303, headers: { location: path } });
}
`;
}

function kebab(value: string): string {
    return value.trim().replace(/([a-z0-9])([A-Z])/g, "$1 $2").split(/[^a-zA-Z0-9]+/).filter(Boolean).map(w => w.toLowerCase()).join("-");
}
