// Auto-generated by ctx.genTypes — do not edit
// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.
type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;

declare global {
    type Session = import("../../../src/$type_Session").Session;
    type Context = import("../../../src/$type_Context").Context;

    interface FnsRegistry {
        config: {
            coerce: Injected<typeof import("../../../src/config/coerce").default>;
            resolve: Injected<typeof import("../../../src/config/resolve").default>;
            validate: Injected<typeof import("../../../src/config/validate").default>;
        };
        db: {
            close: Injected<typeof import("../../../src/db/close").default>;
            conn: Injected<typeof import("../../../src/db/conn").default>;
            exec: Injected<typeof import("../../../src/db/exec").default>;
            query: Injected<typeof import("../../../src/db/query").default>;
            run: Injected<typeof import("../../../src/db/run").default>;
            url: Injected<typeof import("../../../src/db/url").default>;
        };
        dev: {
            build: Injected<typeof import("../../../src/dev/build").default>;
            def: Injected<typeof import("../../../src/dev/def").default>;
            lint: Injected<typeof import("../../../src/dev/lint").default>;
            manifest: Injected<typeof import("../../../src/dev/manifest").default>;
            sync: Injected<typeof import("../../../src/dev/sync").default>;
            test: Injected<typeof import("../../../src/dev/test").default>;
            typecheck: Injected<typeof import("../../../src/dev/typecheck").default>;
            watch: Injected<typeof import("../../../src/dev/watch").default>;
        };
        env: {
            fork: Injected<typeof import("../../../src/env/fork").default>;
            mode: Injected<typeof import("../../../src/env/mode").default>;
            pick: Injected<typeof import("../../../src/env/pick").default>;
        };
        events: {
            emit: Injected<typeof import("../../../src/events/emit").default>;
            reload: Injected<typeof import("../../../src/events/reload").default>;
            subscribe: Injected<typeof import("../../../src/events/subscribe").default>;
        };
        generate: {
            fn: Injected<typeof import("../../../src/generate/fn").default>;
            module: Injected<typeof import("../../../src/generate/module").default>;
            route: Injected<typeof import("../../../src/generate/route").default>;
        };
        http: {
            dispatch: Injected<typeof import("../../../src/http/dispatch").default>;
            loadRoutes: Injected<typeof import("../../../src/http/loadRoutes").default>;
            match: Injected<typeof import("../../../src/http/match").default>;
            middleware: Injected<typeof import("../../../src/http/middleware").default>;
            toResponse: Injected<typeof import("../../../src/http/toResponse").default>;
        };
        lifecycle: {
            order: Injected<typeof import("../../../src/lifecycle/order").default>;
            start: Injected<typeof import("../../../src/lifecycle/start").default>;
            stop: Injected<typeof import("../../../src/lifecycle/stop").default>;
        };
        plugins: {
            add: Injected<typeof import("../../../src/plugins/add").default>;
            list: Injected<typeof import("../../../src/plugins/list").default>;
            remove: Injected<typeof import("../../../src/plugins/remove").default>;
        };
        project: {
            classify: Injected<typeof import("../../../src/project/classify").default>;
            projectRoot: Injected<typeof import("../../../src/project/projectRoot").default>;
            roots: Injected<typeof import("../../../src/project/roots").default>;
            scan: Injected<typeof import("../../../src/project/scan").default>;
        };
        repl: {
            eval: Injected<typeof import("../../../src/repl/eval").default>;
            load: Injected<typeof import("../../../src/repl/load").default>;
        };
    }

    interface RootFns {
    add: Injected<typeof import("./add").default>;
    genTypes: Injected<typeof import("../../../src/genTypes").default>;
    layout: Injected<typeof import("../../../src/$layout").default>;
    list: Injected<typeof import("./list").default>;
    loadFns: Injected<typeof import("../../../src/loadFns").default>;
    migrate: Injected<typeof import("./migrate").default>;
    remove: Injected<typeof import("./remove").default>;
    render: Injected<typeof import("./render").default>;
    toggle: Injected<typeof import("./toggle").default>;
    }
}
export {};
