// Auto-generated by ctx.genTypes — do not edit
declare global {
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        dev: {
        def: typeof import("./dev/def").default;
        sync: typeof import("./dev/sync").default;
        watch: typeof import("./dev/watch").default;
        };
        events: {
        emit: typeof import("./events/emit").default;
        reload: typeof import("./events/reload").default;
        subscribe: typeof import("./events/subscribe").default;
        };
        generate: {
        fn: typeof import("./generate/fn").default;
        module: typeof import("./generate/module").default;
        route: typeof import("./generate/route").default;
        };
        http: {
        loadRoutes: typeof import("./http/loadRoutes").default;
        match: typeof import("./http/match").default;
        start: typeof import("./http/$start").default;
        };
        project: {
        classify: typeof import("./project/classify").default;
        roots: typeof import("./project/roots").default;
        scan: typeof import("./project/scan").default;
        };
        repl: {
        eval: typeof import("./repl/eval").default;
        load: typeof import("./repl/load").default;
        };
    }

    interface RootFns {
    genTypes: typeof import("./genTypes").default;
    layout: typeof import("./$layout").default;
    loadFns: typeof import("./loadFns").default;
    }
}
export {};
