// Auto-generated by ctx.genTypes — do not edit
// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.
type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;

declare global {
    type Session = import("./$type_Session").Session;
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        config: {
            coerce: Injected<typeof import("./config/coerce").default>;
            resolve: Injected<typeof import("./config/resolve").default>;
            validate: Injected<typeof import("./config/validate").default>;
        };
        db: {
            close: Injected<typeof import("./db/close").default>;
            conn: Injected<typeof import("./db/conn").default>;
            exec: Injected<typeof import("./db/exec").default>;
            query: Injected<typeof import("./db/query").default>;
            run: Injected<typeof import("./db/run").default>;
            url: Injected<typeof import("./db/url").default>;
        };
        dev: {
            build: Injected<typeof import("./dev/build").default>;
            def: Injected<typeof import("./dev/def").default>;
            lint: Injected<typeof import("./dev/lint").default>;
            manifest: Injected<typeof import("./dev/manifest").default>;
            sync: Injected<typeof import("./dev/sync").default>;
            test: Injected<typeof import("./dev/test").default>;
            typecheck: Injected<typeof import("./dev/typecheck").default>;
            watch: Injected<typeof import("./dev/watch").default>;
        };
        env: {
            fork: Injected<typeof import("./env/fork").default>;
            mode: Injected<typeof import("./env/mode").default>;
            pick: Injected<typeof import("./env/pick").default>;
        };
        events: {
            emit: Injected<typeof import("./events/emit").default>;
            reload: Injected<typeof import("./events/reload").default>;
            subscribe: Injected<typeof import("./events/subscribe").default>;
        };
        generate: {
            fn: Injected<typeof import("./generate/fn").default>;
            module: Injected<typeof import("./generate/module").default>;
            route: Injected<typeof import("./generate/route").default>;
        };
        hello: {
            world: Injected<typeof import("../examples/hello/src/world").default>;
        };
        http: {
            dispatch: Injected<typeof import("./http/dispatch").default>;
            loadRoutes: Injected<typeof import("./http/loadRoutes").default>;
            match: Injected<typeof import("./http/match").default>;
            middleware: Injected<typeof import("./http/middleware").default>;
            toResponse: Injected<typeof import("./http/toResponse").default>;
        };
        lifecycle: {
            order: Injected<typeof import("./lifecycle/order").default>;
            start: Injected<typeof import("./lifecycle/start").default>;
            stop: Injected<typeof import("./lifecycle/stop").default>;
        };
        plugins: {
            add: Injected<typeof import("./plugins/add").default>;
            list: Injected<typeof import("./plugins/list").default>;
            remove: Injected<typeof import("./plugins/remove").default>;
        };
        project: {
            classify: Injected<typeof import("./project/classify").default>;
            projectRoot: Injected<typeof import("./project/projectRoot").default>;
            roots: Injected<typeof import("./project/roots").default>;
            scan: Injected<typeof import("./project/scan").default>;
        };
        repl: {
            eval: Injected<typeof import("./repl/eval").default>;
            load: Injected<typeof import("./repl/load").default>;
        };
    }

    interface RootFns {
    genTypes: Injected<typeof import("./genTypes").default>;
    layout: Injected<typeof import("./$layout").default>;
    loadFns: Injected<typeof import("./loadFns").default>;
    }

    interface CtxState {
        hello: import("../examples/hello/src/$state_hello").hello;
    }
}
export {};
