// Auto-generated by ctx.genTypes — do not edit
// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.
type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;

declare global {
    type Context = import("./$type_Context").Context;
    type Session = import("./$type_Session").Session;

    interface FnsRegistry {
        agent: {
            callAcp: Injected<typeof import("./agent/callAcp").default>;
            cancel: Injected<typeof import("./agent/cancel").default>;
            checkCredentials: Injected<typeof import("./agent/checkCredentials").default>;
            classifyError: Injected<typeof import("./agent/classifyError").default>;
            clearConnection: Injected<typeof import("./agent/clearConnection").default>;
            closeSession: Injected<typeof import("./agent/closeSession").default>;
            decidePermission: Injected<typeof import("./agent/decidePermission").default>;
            dequeue: Injected<typeof import("./agent/dequeue").default>;
            finishPrompt: Injected<typeof import("./agent/finishPrompt").default>;
            handleClose: Injected<typeof import("./agent/handleClose").default>;
            handleExit: Injected<typeof import("./agent/handleExit").default>;
            injectContext: Injected<typeof import("./agent/injectContext").default>;
            messages: Injected<typeof import("./agent/messages").default>;
            openSession: Injected<typeof import("./agent/openSession").default>;
            options: Injected<typeof import("./agent/options").default>;
            prompt: Injected<typeof import("./agent/prompt").default>;
            publish: Injected<typeof import("./agent/publish").default>;
            readStderr: Injected<typeof import("./agent/readStderr").default>;
            receive: Injected<typeof import("./agent/receive").default>;
            resetSession: Injected<typeof import("./agent/resetSession").default>;
            resolveCommand: Injected<typeof import("./agent/resolveCommand").default>;
            restoreSession: Injected<typeof import("./agent/restoreSession").default>;
            runPrompt: Injected<typeof import("./agent/runPrompt").default>;
            saveMessage: Injected<typeof import("./agent/saveMessage").default>;
            saveState: Injected<typeof import("./agent/saveState").default>;
            search: Injected<typeof import("./agent/search").default>;
            sendPrompt: Injected<typeof import("./agent/sendPrompt").default>;
            setConfig: Injected<typeof import("./agent/setConfig").default>;
            setMode: Injected<typeof import("./agent/setMode").default>;
            settleTools: Injected<typeof import("./agent/settleTools").default>;
            start: Injected<typeof import("./agent/start").default>;
            stop: Injected<typeof import("./agent/stop").default>;
            trackTiming: Injected<typeof import("./agent/trackTiming").default>;
            writeHelpers: Injected<typeof import("./agent/writeHelpers").default>;
        };
        aidbox: {
            compose: Injected<typeof import("../plugins/aidbox/src/compose").default>;
            request: Injected<typeof import("../plugins/aidbox/src/request").default>;
            sql: Injected<typeof import("../plugins/aidbox/src/sql").default>;
            writeCompose: Injected<typeof import("../plugins/aidbox/src/writeCompose").default>;
        };
        app: {
            patients: {
                fhir: Injected<typeof import("../../../workspace-template-2/src/patients/fhir").default>;
                name: Injected<typeof import("../../../workspace-template-2/src/patients/name").default>;
                search: Injected<typeof import("../../../workspace-template-2/src/patients/search").default>;
            };
        };
        chart: {
            data: Injected<typeof import("../plugins/chart/src/data").default>;
            load: Injected<typeof import("../plugins/chart/src/load").default>;
            local: Injected<typeof import("../plugins/chart/src/local").default>;
            preview: Injected<typeof import("../plugins/chart/src/preview").default>;
            render: Injected<typeof import("../plugins/chart/src/render").default>;
            theme: Injected<typeof import("../plugins/chart/src/theme").default>;
        };
        chat: {
            answer: Injected<typeof import("./chat/answer").default>;
            bubble: Injected<typeof import("./chat/bubble").default>;
            column: Injected<typeof import("./chat/column").default>;
            composer: Injected<typeof import("./chat/composer").default>;
            controls: Injected<typeof import("./chat/controls").default>;
            error: Injected<typeof import("./chat/error").default>;
            escape: Injected<typeof import("./chat/escape").default>;
            markdown: Injected<typeof import("./chat/markdown").default>;
            models: Injected<typeof import("./chat/models").default>;
            notice: Injected<typeof import("./chat/notice").default>;
            plan: Injected<typeof import("./chat/plan").default>;
            queue: Injected<typeof import("./chat/queue").default>;
            reply: Injected<typeof import("./chat/reply").default>;
            runState: Injected<typeof import("./chat/runState").default>;
            send: Injected<typeof import("./chat/send").default>;
            thought: Injected<typeof import("./chat/thought").default>;
            toolMeta: Injected<typeof import("./chat/toolMeta").default>;
            toolRow: Injected<typeof import("./chat/toolRow").default>;
            tools: Injected<typeof import("./chat/tools").default>;
            transcript: Injected<typeof import("./chat/transcript").default>;
            usage: Injected<typeof import("./chat/usage").default>;
        };
        cli: {
            list: Injected<typeof import("./cli/list").default>;
            parse: Injected<typeof import("./cli/parse").default>;
            run: Injected<typeof import("./cli/run").default>;
        };
        config: {
            coerce: Injected<typeof import("./config/coerce").default>;
            resolve: Injected<typeof import("./config/resolve").default>;
            validate: Injected<typeof import("./config/validate").default>;
        };
        db: {
            close: Injected<typeof import("./db/close").default>;
            conn: Injected<typeof import("./db/conn").default>;
            exec: Injected<typeof import("./db/exec").default>;
            insert: Injected<typeof import("./db/insert").default>;
            q: Injected<typeof import("./db/q").default>;
            query: Injected<typeof import("./db/query").default>;
            run: Injected<typeof import("./db/run").default>;
            sql: Injected<typeof import("./db/sql").default>;
            url: Injected<typeof import("./db/url").default>;
        };
        dev: {
            build: Injected<typeof import("./dev/build").default>;
            def: Injected<typeof import("./dev/def").default>;
            lint: Injected<typeof import("./dev/lint").default>;
            manifest: Injected<typeof import("./dev/manifest").default>;
            sync: Injected<typeof import("./dev/sync").default>;
            test: Injected<typeof import("./dev/test").default>;
            typecheck: Injected<typeof import("./dev/typecheck").default>;
            watch: Injected<typeof import("./dev/watch").default>;
        };
        env: {
            fork: Injected<typeof import("./env/fork").default>;
            mode: Injected<typeof import("./env/mode").default>;
            pick: Injected<typeof import("./env/pick").default>;
        };
        events: {
            emit: Injected<typeof import("./events/emit").default>;
            reload: Injected<typeof import("./events/reload").default>;
            subscribe: Injected<typeof import("./events/subscribe").default>;
        };
        filemanager: {
            claim: Injected<typeof import("../plugins/filemanager/src/claim").default>;
            crumbs: Injected<typeof import("../plugins/filemanager/src/crumbs").default>;
            icon: Injected<typeof import("../plugins/filemanager/src/icon").default>;
            list: Injected<typeof import("../plugins/filemanager/src/list").default>;
            listing: Injected<typeof import("../plugins/filemanager/src/listing").default>;
            render: Injected<typeof import("../plugins/filemanager/src/render").default>;
        };
        generate: {
            fn: Injected<typeof import("./generate/fn").default>;
            module: Injected<typeof import("./generate/module").default>;
            route: Injected<typeof import("./generate/route").default>;
        };
        hooks: {
            first: Injected<typeof import("./hooks/first").default>;
            list: Injected<typeof import("./hooks/list").default>;
            register: Injected<typeof import("./hooks/register").default>;
            run: Injected<typeof import("./hooks/run").default>;
        };
        http: {
            dispatch: Injected<typeof import("./http/dispatch").default>;
            loadRoutes: Injected<typeof import("./http/loadRoutes").default>;
            match: Injected<typeof import("./http/match").default>;
            middleware: Injected<typeof import("./http/middleware").default>;
            toResponse: Injected<typeof import("./http/toResponse").default>;
        };
        lifecycle: {
            order: Injected<typeof import("./lifecycle/order").default>;
            start: Injected<typeof import("./lifecycle/start").default>;
            stop: Injected<typeof import("./lifecycle/stop").default>;
        };
        log: {
            debug: Injected<typeof import("./log/debug").default>;
            emit: Injected<typeof import("./log/emit").default>;
            error: Injected<typeof import("./log/error").default>;
            info: Injected<typeof import("./log/info").default>;
            level: Injected<typeof import("./log/level").default>;
            warn: Injected<typeof import("./log/warn").default>;
        };
        migrate: {
            down: Injected<typeof import("./migrate/down").default>;
            status: Injected<typeof import("./migrate/status").default>;
            up: Injected<typeof import("./migrate/up").default>;
        };
        page: {
            click: Injected<typeof import("./page/click").default>;
            eval: Injected<typeof import("./page/eval").default>;
            fill: Injected<typeof import("./page/fill").default>;
            open: Injected<typeof import("./page/open").default>;
            openTab: Injected<typeof import("./page/openTab").default>;
            point: Injected<typeof import("./page/point").default>;
            say: Injected<typeof import("./page/say").default>;
            state: Injected<typeof import("./page/state").default>;
            submit: Injected<typeof import("./page/submit").default>;
            tabs: Injected<typeof import("./page/tabs").default>;
            text: Injected<typeof import("./page/text").default>;
            tour: Injected<typeof import("./page/tour").default>;
        };
        plugins: {
            add: Injected<typeof import("./plugins/add").default>;
            catalog: Injected<typeof import("./plugins/catalog").default>;
            describe: Injected<typeof import("./plugins/describe").default>;
            fetch: Injected<typeof import("./plugins/fetch").default>;
            list: Injected<typeof import("./plugins/list").default>;
            panel: Injected<typeof import("./plugins/panel").default>;
            readDeclared: Injected<typeof import("./plugins/readDeclared").default>;
            reload: Injected<typeof import("./plugins/reload").default>;
            remove: Injected<typeof import("./plugins/remove").default>;
        };
        preview: {
            url: Injected<typeof import("../plugins/preview/src/url").default>;
        };
        processes: {
            card: Injected<typeof import("../plugins/services/src/card").default>;
            cards: Injected<typeof import("../plugins/services/src/cards").default>;
            escape: Injected<typeof import("../plugins/services/src/escape").default>;
            list: Injected<typeof import("../plugins/services/src/list").default>;
            logs: Injected<typeof import("../plugins/services/src/logs").default>;
            panel: Injected<typeof import("../plugins/services/src/panel").default>;
        };
        project: {
            classify: Injected<typeof import("./project/classify").default>;
            pluginPaths: Injected<typeof import("./project/pluginPaths").default>;
            projectRoot: Injected<typeof import("./project/projectRoot").default>;
            roots: Injected<typeof import("./project/roots").default>;
            scan: Injected<typeof import("./project/scan").default>;
            workdir: Injected<typeof import("./project/workdir").default>;
        };
        questionnaire: {
            generate: Injected<typeof import("../plugins/questionnaire/src/generate").default>;
            load: Injected<typeof import("../plugins/questionnaire/src/load").default>;
            local: Injected<typeof import("../plugins/questionnaire/src/local").default>;
            preview: Injected<typeof import("../plugins/questionnaire/src/preview").default>;
            render: Injected<typeof import("../plugins/questionnaire/src/render").default>;
            results: Injected<typeof import("../plugins/questionnaire/src/results").default>;
            search: Injected<typeof import("../plugins/questionnaire/src/search").default>;
            styles: Injected<typeof import("../plugins/questionnaire/src/styles").default>;
        };
        repl: {
            eval: Injected<typeof import("./repl/eval").default>;
            load: Injected<typeof import("./repl/load").default>;
        };
        services: {
            captureLogs: Injected<typeof import("./services/captureLogs").default>;
            env: Injected<typeof import("./services/env").default>;
            freePort: Injected<typeof import("./services/freePort").default>;
            logs: Injected<typeof import("./services/logs").default>;
            manifest: Injected<typeof import("./services/manifest").default>;
            probeReady: Injected<typeof import("./services/probeReady").default>;
            resolve: Injected<typeof import("./services/resolve").default>;
            restart: Injected<typeof import("./services/restart").default>;
            spawn: Injected<typeof import("./services/spawn").default>;
            start: Injected<typeof import("./services/start").default>;
            startAll: Injected<typeof import("./services/startAll").default>;
            status: Injected<typeof import("./services/status").default>;
            stop: Injected<typeof import("./services/stop").default>;
            superviseExit: Injected<typeof import("./services/superviseExit").default>;
            track: Injected<typeof import("./services/track").default>;
            waitReady: Injected<typeof import("./services/waitReady").default>;
        };
        ui: {
            attr: Injected<typeof import("./ui/attr").default>;
            badge: Injected<typeof import("./ui/badge").default>;
            box: Injected<typeof import("./ui/box").default>;
            button: Injected<typeof import("./ui/button").default>;
            field: Injected<typeof import("./ui/field").default>;
            form: Injected<typeof import("./ui/form").default>;
            notice: Injected<typeof import("./ui/notice").default>;
            page: Injected<typeof import("./ui/page").default>;
            row: Injected<typeof import("./ui/row").default>;
            tabs: Injected<typeof import("./ui/tabs").default>;
        };
        viewdef: {
            columns: Injected<typeof import("../plugins/viewdef/src/columns").default>;
            load: Injected<typeof import("../plugins/viewdef/src/load").default>;
            local: Injected<typeof import("../plugins/viewdef/src/local").default>;
            materialize: Injected<typeof import("../plugins/viewdef/src/materialize").default>;
            preview: Injected<typeof import("../plugins/viewdef/src/preview").default>;
            rows: Injected<typeof import("../plugins/viewdef/src/rows").default>;
            table: Injected<typeof import("../plugins/viewdef/src/table").default>;
        };
    }

    interface RootFns {
    genTypes: Injected<typeof import("./genTypes").default>;
    layout: Injected<typeof import("./$layout").default>;
    loadFns: Injected<typeof import("./loadFns").default>;
    }

    namespace types {
        namespace agent {
            type Message = import("./agent/$type_Message").Message;
        }
        namespace db {
            type Query = import("./db/$type_Query").Query;
        }
        namespace log {
            type LogRecord = import("./log/$type_LogRecord").LogRecord;
        }
        namespace page {
            type Descriptor = import("./page/$type_Descriptor").Descriptor;
        }
        namespace services {
            type Line = import("./services/$type_Line").Line;
            type Service = import("./services/$type_Service").Service;
            type Spec = import("./services/$type_Spec").Spec;
        }
    }

    interface CtxState {
        agent: import("./agent/$state_agent").agent;
        appRoots: import("./project/$state_appRoots").appRoots;
        page: import("./page/$state_page").page;
        plugins: import("./plugins/$state_plugins").plugins;
        services: import("./services/$state_services").services;
    }
}
export {};
