// Generate src/ctx_ns.d.ts from the project scan. The registry nests by
// directory (src/a/b/c.ts → ctx.fns.a.b.c), so types must nest too — we build
// a tree from moduleDir segments and emit nested interface bodies (fns) and
// nested `namespace` blocks (types). Each fn type is wrapped in Injected<> —
// ctx/session stripped, matching the real call shape.
type Node = { fns: Record<string, string>; types: Record<string, string>; children: Record<string, Node> };
const makeNode = (): Node => ({ fns: {}, types: {}, children: {} });
const hasFns = (n: Node): boolean => Object.keys(n.fns).length > 0 || Object.values(n.children).some(hasFns);
const hasTypes = (n: Node): boolean => Object.keys(n.types).length > 0 || Object.values(n.children).some(hasTypes);
// Defense-in-depth: dev.lint forbids non-identifier names, but if one slips in
// (hand-edited file before lint runs), quote FnsRegistry member keys so a single
// bad name doesn't break the whole d.ts. Namespaces/type-aliases can't be quoted.
const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const k = (s: string): string => IDENT.test(s) ? s : JSON.stringify(s);

export default async function (ctx: Context, _session: Session | null, _opts?: {}) {
    const srcDir = import.meta.dir;
    const entries = await ctx.fns.project.scan({});

    const globals: string[] = [];   // root $type_Name.ts
    const rootFns: string[] = [];   // root $name.ts → ctx.<name>
    const root = makeNode();
    const moduleDirs = new Set<string>();
    let typeCount = 0;

    const walk = (segments: string[]): Node => {
        let n = root;
        for (const s of segments) n = (n.children[s] ??= makeNode());
        return n;
    };

    for (const entry of entries) {
        if (entry.kind !== 'fn' && entry.kind !== 'type') continue;
        const importPath = './' + entry.rel.replace(/\.ts$/, '');
        if (entry.kind === 'type') {
            typeCount++;
            if (entry.moduleDir === '.') globals.push(`    type ${entry.typeName} = import("${importPath}").${entry.typeName};`);
            else walk(entry.moduleDir.split('/')).types[entry.typeName] = importPath;
        } else {
            if (entry.moduleDir === '.') rootFns.push(`    ${entry.runtimeName}: Injected<typeof import("${importPath}").default>;`);
            else { walk(entry.moduleDir.split('/')).fns[entry.runtimeName] = importPath; moduleDirs.add(entry.moduleDir); }
        }
    }

    const emitFns = (node: Node, ind: string): string[] => {
        const out: string[] = [];
        for (const name of Object.keys(node.fns).sort())
            out.push(`${ind}${k(name)}: Injected<typeof import("${node.fns[name]}").default>;`);
        for (const seg of Object.keys(node.children).sort()) {
            const child = node.children[seg]!;
            if (!hasFns(child)) continue;
            out.push(`${ind}${k(seg)}: {`, ...emitFns(child, ind + '    '), `${ind}};`);
        }
        return out;
    };
    const emitTypes = (node: Node, ind: string): string[] => {
        const out: string[] = [];
        for (const name of Object.keys(node.types).sort()) {
            if (!IDENT.test(name)) { console.warn(`[genTypes] skip non-identifier type "${name}"`); continue; }
            out.push(`${ind}type ${name} = import("${node.types[name]}").${name};`);
        }
        for (const seg of Object.keys(node.children).sort()) {
            const child = node.children[seg]!;
            if (!hasTypes(child)) continue;
            if (!IDENT.test(seg)) { console.warn(`[genTypes] skip non-identifier namespace "${seg}"`); continue; }
            out.push(`${ind}namespace ${seg} {`, ...emitTypes(child, ind + '    '), `${ind}}`);
        }
        return out;
    };

    const lines: string[] = [
        '// Auto-generated by ctx.genTypes — do not edit',
        '// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.',
        'type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;',
        '',
        'declare global {',
        ...globals,
        '',
        '    interface FnsRegistry {',
        ...emitFns(root, '        '),
        '    }',
        '',
        '    interface RootFns {',
        ...rootFns.sort(),
        '    }',
    ];
    if (hasTypes(root)) {
        lines.push('', '    namespace types {', ...emitTypes(root, '        '), '    }');
    }
    lines.push('}', 'export {};', '');

    const out = srcDir + '/ctx_ns.d.ts';
    await Bun.write(out, lines.join('\n'));
    console.log('[genTypes] ' + rootFns.length + ' root fn(s), ' + moduleDirs.size + ' module(s), ' + typeCount + ' type(s) → src/ctx_ns.d.ts');
    return { roots: rootFns.length, modules: moduleDirs.size, types: typeCount };
}
