// Generate src/ctx_ns.d.ts from the project scan. Every fn's registry entry
// is wrapped in Injected<> — ctx & session are stripped from the public
// signature because the ctx.fns Proxy injects them at call time.
export default async function (ctx: Context, _session: Session | null, _opts?: {}) {
    const srcDir = import.meta.dir;
    const entries = await ctx.fns.project.scan({});

    const globals: string[] = [];
    const typesByModule: Record<string, string[]> = {};
    const fnsByModule: Record<string, string[]> = {};
    const rootFns: string[] = [];

    for (const entry of entries) {
        if (entry.kind !== 'fn' && entry.kind !== 'type') continue;
        const importPath = './' + entry.rel.replace(/\.ts$/, '');

        if (entry.kind === 'type') {
            const line = 'type ' + entry.typeName + ' = import("' + importPath + '").' + entry.typeName + ';';
            if (entry.moduleDir === '.') {
                globals.push('    ' + line);
            } else {
                const bucket = (typesByModule[entry.moduleDir] ??= []);
                bucket.push('            ' + line);
            }
            continue;
        }

        const line = entry.runtimeName + ': Injected<typeof import("' + importPath + '").default>;';
        if (entry.moduleDir === '.') {
            rootFns.push('    ' + line);
        } else {
            const bucket = (fnsByModule[entry.moduleDir] ??= []);
            bucket.push('        ' + line);
        }
    }

    const lines: string[] = [
        '// Auto-generated by ctx.genTypes — do not edit',
        '// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.',
        'type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;',
        '',
        'declare global {',
        ...globals,
        '',
        '    interface FnsRegistry {',
    ];
    for (const [mod, items] of Object.entries(fnsByModule).sort()) {
        lines.push('        ' + mod + ': {');
        lines.push(...items.sort());
        lines.push('        };');
    }
    lines.push('    }', '', '    interface RootFns {');
    lines.push(...rootFns.sort());
    lines.push('    }');

    if (Object.keys(typesByModule).length > 0) {
        lines.push('', '    namespace types {');
        for (const [mod, items] of Object.entries(typesByModule).sort()) {
            lines.push('        namespace ' + mod + ' {');
            lines.push(...items.sort());
            lines.push('        }');
        }
        lines.push('    }');
    }

    lines.push('}', 'export {};', '');

    const out = srcDir + '/ctx_ns.d.ts';
    await Bun.write(out, lines.join('\n'));
    const typesCount = globals.length + Object.values(typesByModule).flat().length;
    console.log('[genTypes] ' + rootFns.length + ' root fn(s), ' + Object.keys(fnsByModule).length + ' module(s), ' + typesCount + ' type(s) → src/ctx_ns.d.ts');
    return { roots: rootFns.length, modules: Object.keys(fnsByModule).length, types: typesCount };
}
